apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres
  namespace: k8s-campuscart
  labels:
    app: postgres
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: postgres
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - k8s-campuscart